# Generated by Django 2.0.7 on 2018-08-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
    ]
